// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailcarTrips.Server.Data;

#nullable disable

namespace RailcarTrips.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.AppTimeZone", b =>
                {
                    b.Property<int>("TimeZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UtcOffSet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("TimeZoneId");

                    b.HasIndex("TimeZoneName")
                        .IsUnique();

                    b.ToTable("TimeZones");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TimeZoneId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("TimeZoneId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EventCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTimeLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EventTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("CityId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EventCodeId");

                    b.HasIndex("EventTimeUtc");

                    b.HasIndex("TripId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.EventCode", b =>
                {
                    b.Property<int>("EventCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("EventCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EventCodes");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndEventTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartEventTime")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("TotalTime")
                        .HasColumnType("time(6)");

                    b.HasKey("TripId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OriginCityId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.City", b =>
                {
                    b.HasOne("RailcarTrips.Server.Data.Entities.AppTimeZone", "TimeZone")
                        .WithMany("Cities")
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeZone");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Event", b =>
                {
                    b.HasOne("RailcarTrips.Server.Data.Entities.City", "City")
                        .WithMany("Events")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Server.Data.Entities.EventCode", "EventCode")
                        .WithMany("Events")
                        .HasForeignKey("EventCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RailcarTrips.Server.Data.Entities.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("EventCode");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Trip", b =>
                {
                    b.HasOne("RailcarTrips.Server.Data.Entities.City", "DestinationCity")
                        .WithMany()
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RailcarTrips.Server.Data.Entities.City", "OriginCity")
                        .WithMany()
                        .HasForeignKey("OriginCityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationCity");

                    b.Navigation("OriginCity");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.AppTimeZone", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.City", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.EventCode", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RailcarTrips.Server.Data.Entities.Trip", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
